% --- FILE START: useExample02_ExperimentalETS.m ---
% Example script demonstrating loading experimental data, processing,
% and applying two ETS strategies (NDC-only vs Pnv) using the OO framework.
% Assumes necessary calibration files (VC_not, parameters) are available.

clear; clc; close all;

fprintf('=== USE EXAMPLE 02: Experimental Data ETS Comparison ===\n');

% --- Configuration ---
expDataSourcePath = 'C:\Users\alexa\experimental_data\outros\Sinais_EEG'; % <<< SET THIS PATH
resultsSavePath = fullfile(expDataSourcePath, 'OO_Results'); % Subfolder for results

% Select subset of subjects and stimuli for demonstration
subjectsToLoad = [1, 2, 3]; % e.g., 'Ab', 'An', 'Bb'
stimuliToLoad = [3];       % e.g., '50dB' (index 3)

% MSC Analysis Parameters (Match parameters used in original calibration if possible)
% Example: Use parameters derived for Mmax=240 as in sinal_eeg_M*.m scripts
% We need to select ONE parameter set for MSC calculation here, or loop through them.
% Let's choose parameters approximating one set from the original pareto plots.
% Example: From a Pareto point {Mmin=20, Mstep=16} for Mmax=240
mscParamSettings.Method = 'fixedSize';
mscParamSettings.StartWindow = 20; % Mmin equivalent
mscParamSettings.WindowStepSize = 16;% Mstep equivalent

% Strategy Parameters (MUST correspond to the MSC params chosen)
% These would typically be loaded from files generated by calibration scripts
% like funcao_NDC_alfaCorrigido_Mmax.m or Teste_PD_Pnv.m

% --- Placeholder Loading - Replace with actual loading ---
% These are EXAMPLE values - they NEED to be the calibrated ones for meaningful results
% matching the chosen MSC parameters (Mmin=20, Mstep=16, Mmax=240).
alpha_per_test = 0.05; % Example, might need calibrated value
etsParamsNDC.alpha = alpha_per_test;
etsParamsNDC.NDC = 3; % Example NDC value

etsParamsPnv = etsParamsNDC; % Start with same alpha/NDC
% Load VC_not corresponding to Mmax = 240 and the alpha used for its generation
vc_not_filename = 'VC_not_Unitario_Mmax_240_alfa_0.05.mat'; % <<< CHECK FILENAME AND PATH
try
    vc_data = load(fullfile(expDataSourcePath, vc_not_filename), 'VC_not');
    etsParamsPnv.VC_not = vc_data.VC_not;
    fprintf('Loaded VC_not from %s\n', vc_not_filename);
catch ME_vcnot
     warning('Could not load VC_not file "%s". ETS_Pnv strategy will likely fail or use dummy thresholds. Error: %s', vc_not_filename, ME_vcnot.message);
     % Provide dummy VC_not to allow script structure to run, but results invalid
      etsParamsPnv.VC_not = zeros(1, 240) - Inf; % Dummy: never triggers futility
end
% -----------------------------------------------------

if ~exist(resultsSavePath, 'dir'); mkdir(resultsSavePath); end
if ~exist(expDataSourcePath, 'dir'); error('Experimental data source path does not exist: %s', expDataSourcePath); end

% --- 1. Setup DataManager (Experimental Mode) ---
dataMgr = DataManager('exp', expDataSourcePath, resultsSavePath);
% Load the selected experimental data
dataMgr = dataMgr.loadBulkExperiments(subjectsToLoad, stimuliToLoad);

% --- 2. Setup SignalProcessor ---
processor = SignalProcessor(dataMgr);
processor.ZanoteliEnable = true; % Use Zanoteli preprocessing as in original scripts
processor.FilterEnable = false;  % Disable filtering (Antunes) if not used in original ETS comparison
% Process the loaded experimental data
processor = processor.processBulkData(dataMgr);

% --- 3. Setup MSCAnalyzer ---
% We are testing ONE specific parameter set (Mmin=20, Mstep=16)
mscAnalyzer = MSCAnalyzer(mscParamSettings.Method, ...
                          'StartWindow', mscParamSettings.StartWindow, ...
                          'WindowStepSize', mscParamSettings.WindowStepSize);
% Analyze MSC just for this single parameter set
% Pass the parameter values directly for single analysis run
mscAnalyzer = mscAnalyzer.analyzeBulkMSC(processor, ...
                    'StartWindows', mscParamSettings.StartWindow, ...
                    'WindowStepSizes', mscParamSettings.WindowStepSize);

% --- 4 & 5. Setup and Run Tester for ETS_NDC ---
fprintf('\n--- Testing ETS_NDC Strategy ---\n');
etsStrategy_ndc = ETSStrategy(false); % UseFutility = false
tester_ets_ndc = SequentialTester(etsStrategy_ndc, dataMgr, mscAnalyzer);
% Run the test using the loaded/defined parameters for NDC
tester_ets_ndc = tester_ets_ndc.runBulkTest(etsParamsNDC); % scalar params for all subjects/stimuli
% Performance calculation is not applicable in experimental mode

% --- 4 & 5. Setup and Run Tester for ETS_Pnv ---
fprintf('\n--- Testing ETS_Pnv Strategy ---\n');
etsStrategy_pnv = ETSStrategy(true); % UseFutility = true
tester_ets_pnv = SequentialTester(etsStrategy_pnv, dataMgr, mscAnalyzer);
% Run the test using the loaded/defined parameters for Pnv (includes VC_not)
tester_ets_pnv = tester_ets_pnv.runBulkTest(etsParamsPnv); % scalar params
% Performance calculation is not applicable

% --- 6. Visualize Results ---
% Note: Can't easily calculate aggregate performance like TPR/FPR without ground truth.
% We can visualize the test progression for specific examples.

visualizer_ets_ndc = Visualizer(dataMgr, mscAnalyzer, tester_ets_ndc);
visualizer_ets_pnv = Visualizer(dataMgr, mscAnalyzer, tester_ets_pnv);

% Plot MSC vs Thresholds for Subject 1, Stimulus 3 (first loaded), ParamSet (1,1), Channel 1
subjIdxToPlot = subjectsToLoad(1);
stimIdxToPlot = stimuliToLoad(1);
p1IdxToPlot = 1; % Only one parameter set was analyzed
p2IdxToPlot = 1;
chanToPlot = 1;

try
    fig_ndc = visualizer_ets_ndc.plotMSCandThresholds(stimIdxToPlot, subjIdxToPlot, p1IdxToPlot, p2IdxToPlot, chanToPlot);
    title(fig_ndc.CurrentAxes, sprintf('ETS NDC Run: Subject %d, Stimulus %d, Chan %d', subjIdxToPlot, stimIdxToPlot, chanToPlot));
catch ME_plot_ndc
    warning('Could not plot ETS NDC example: %s', ME_plot_ndc.message);
end

try
    fig_pnv = visualizer_ets_pnv.plotMSCandThresholds(stimIdxToPlot, subjIdxToPlot, p1IdxToPlot, p2IdxToPlot, chanToPlot);
     title(fig_pnv.CurrentAxes, sprintf('ETS Pnv Run: Subject %d, Stimulus %d, Chan %d', subjIdxToPlot, stimIdxToPlot, chanToPlot));
catch ME_plot_pnv
     warning('Could not plot ETS Pnv example: %s', ME_plot_pnv.message);
end

% --- Further Analysis (Manual/Custom) ---
% To replicate original results like TXD, FP (using noise bins), TimeM:
% 1. Extract final decisions and stopping stages from tester_*.TestDecisions and tester_*.StoppingStages.
% 2. Define signal bins (binsM) and noise bins (binsR) based on experimental setup (e.g., from loaded 'binsM').
% 3. Aggregate decisions across subjects/stimuli for the chosen parameter set.
%    - TXD: Percentage of signal bins where final decision is 1.
%    - FP: Percentage of noise bins where final decision is 1.
% 4. Calculate average stopping time (TimeM) based on stopping stages and epoch durations (might need epoch info from MSCAnalyzer).
% This requires custom scripting using the results stored in the tester objects.

fprintf('\n--- Experimental Analysis Notes ---\n');
fprintf('Visualizations show example runs for Subject %d, Stimulus %d, Channel %d.\n', subjIdxToPlot, stimIdxToPlot, chanToPlot);
fprintf('To calculate aggregate TXD, FP, TimeM as in original scripts:\n');
fprintf('  - Manually define signal/noise frequency bins (e.g., based on loaded "binsM").\n');
fprintf('  - Access results from tester_ets_ndc.TestDecisions{stimIdx, subjIdx, 1, 1}, etc.\n');
fprintf('  - Aggregate decisions and stopping stages across subjects.\n');
fprintf('  - Calculate detection rates and average stopping times.\n');

fprintf('\n=== USE EXAMPLE 02 COMPLETE ===\n');